server:
  port: 8081

spring:
  application:
    name: simple-rpc-provider-test-interface

simple:
  rpc:
    register:
      host: 127.0.0.1
      port: 6379
      password: 123456
      register-type: redis