server:
  port: 8883
simple:
  rpc:
    register:
      address: redis://127.0.0.1:6379
      password: 123456
    base:
      load-balance-rule: random-weight
      serializer: serializer
      weights: 50
