server:
  port: 9999
spring:
  application:
    name: simple-rpc-statistic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 970412@wcx.com
    url: 127.0.0.1
  # Redis服务器连接端口
  redis:
    port: 6379
    # Redis服务器地址
    host: 192.168.100.31
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 5000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

