server:
  port: 8082

spring:
  application:
    name: simple-rpc-consumer-test
simple:
  rpc:
    thread:
      pool:
        core-pool-size: 10
        keep-alive-time: 60
        queue-size: 1000
        maximum-pool-size: 100
